spring:
  application:
    name: technology-portfolio-service
  
  profiles:
    active: dev
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/portfolio
    username: ${DB_USERNAME:portfolio_user}
    password: ${DB_PASSWORD:portfolio_password}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  
  flyway:
    enabled: true  # Re-enabled with Flyway 11.x PostgreSQL 15 support
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  # JWT Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://api-gateway:8080}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://api-gateway:8080/.well-known/jwks.json}
          # For HMAC-based JWT validation (development)
          secret: ${JWT_SECRET:your-256-bit-secret-key-here-for-development-only}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.company.techportfolio: DEBUG
    org.springframework.security: DEBUG
    io.r2dbc: DEBUG  # Enable R2DBC logging for debugging
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:techportfolio_portfolio}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m 