# UAT Environment Configuration
# Profile: uat
# Usage: --spring.profiles.active=uat

server:
  port: 8080

spring:
  profiles:
    active: uat
  cloud:
    gateway:
      enabled: true
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
                - private-key-location: classpath:saml/saml-signing.key
                  certificate-location: classpath:saml/saml-signing.crt
            assertingparty:
              metadata-uri: ${SAML_IDP_METADATA_URL:https://uat-idp.company.com/simplesaml/saml2/idp/metadata.php}
              entity-id: https://uat-idp.company.com/simplesaml/saml2/idp/metadata.php
              verification:
                credentials:
                  - certificate-location: classpath:saml/idp-verification.crt

# JWT Configuration for UAT
jwt:
  secret: ${JWT_SECRET:uat-jwt-secret-key-512-bits-minimum-for-HS512-algorithm}
  expiration: 3600 # 1 hour in seconds

# Eureka Service Discovery (UAT)
eureka:
  client:
    service-url:
      defaultZone: http://uat-eureka.company.com:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

# Service URLs for UAT Environment
services:
  authorization:
    url: http://uat-auth.company.com:8080
  audit:
    url: http://uat-audit.company.com:8080
  user-management:
    url: http://uat-users.company.com:8080
  timeout: 10s  # Longer timeout for UAT

# Logging for UAT
logging:
  level:
    com.company.techportfolio: INFO
    org.springframework.security: WARN
    org.springframework.cloud.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SAML Configuration for UAT
saml:
  idp:
    metadata-url: ${SAML_IDP_METADATA_URL:https://uat-idp.company.com/simplesaml/saml2/idp/metadata.php}
    entity-id: ${SAML_IDP_ENTITY_ID:https://uat-idp.company.com/simplesaml/saml2/idp/metadata.php}
  sp:
    entity-id: ${SAML_SP_ENTITY_ID:https://uat-gateway.company.com}
    base-url: ${SAML_SP_BASE_URL:https://uat-gateway.company.com}

# UAT-specific settings
uat:
  monitoring:
    enabled: true
    metrics-collection: true
  security:
    strict-ssl: true
    cors:
      allowed-origins: ["https://uat-frontend.company.com"] 